### ISSUE TITLE
Redo the walls

### ISSUE THREAD

**Issue by guemax** [guemax/GameOff2021#4]
Due to a bevel modifier in Blender, the walls do not look good when put together. Redo them and integrate them into a new labyrinth.

**TODO**:

- [x] Redo the wall in Blender
- [x] Import it in Godot and save as mesh library
- [x] Redo the labyrinth
